[package]
name = "day-4"
version = "0.1.0"
authors = ["Julien Faixo <julien@faixo.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "day_4"
path = "src/lib.rs"

[dependencies]
regex = "1.4.2"
